name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-app
    steps:
      - name: Setup whatchanged
        uses: release-lab/setup-whatchanged@v1
        with:
          version: v0.5.7

      - name: Changelog generate
        run: |
          whatchanged --project=https://github.com/gizmo-ds/vrchat-cache-mover.git --branch=main --output=CHANGELOG.md

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Archive application
        run: zip -r ./vrchat-cache-mover.zip .

      - name: Generate checksums
        run: sha256sum vrchat-cache-mover.zip > checksums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            checksums.txt
            vrchat-cache-mover.zip

  build-app:
    name: Build application
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: "7.1.8"

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: Setup Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: pnpm i

      - name: Build application
        run: |
          pnpm esno scripts/version.ts
          pnpm tauri build
          mv src-tauri/target/release/*.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "app"
          path: |
            *.exe
            LICENSE
